"""Add Request, Content, Item tables

Revision ID: 35ec7d78b091
Revises: a5b8ca351206
Create Date: 2018-10-26 23:59:28.969231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ec7d78b091'
down_revision = 'a5b8ca351206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_of_order', sa.DateTime(), nullable=True),
    sa.Column('placed', sa.Boolean(), nullable=True),
    sa.Column('placed_by', sa.Integer(), nullable=True),
    sa.Column('fulfilled_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fulfilled_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['placed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('req_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['req_id'], ['request.id'], ),
    sa.PrimaryKeyConstraint('req_id', 'item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content')
    op.drop_table('request')
    op.drop_table('item')
    # ### end Alembic commands ###
